### ISSUE TITLE
Add support for file uploads

### ISSUE THREAD

**Issue by thefosk** [Runscope/httpbin#87] opened 2013-03-11 20:34 UTC
It would be cool to add a `/post/upload` endpoint, which returns the file size of the uploaded object.

**Comment by nishanov** [comment] 2015-10-05 05:07
Hi there. Any progress here?

**Comment by sigmavirus24** [comment] 2015-10-05 13:12
Since this already exists, I'm inclined to close this unless there is some further clarification on why this needs to differ from `/post`.

**Comment by kennethreitz** [comment] 2015-11-18 19:55
This is indeed what `/post` was intended for.

**Closed** 2015-11-18 19:57 UTC
Labels: feature-request

**Comment by moy** [comment] 2017-10-27 10:46
It would be nice to have an `<input type="file">` on http://httpbin.org/forms/post, so that we can easily test the file upload from a form.

**Comment by iBasit** [comment] 2018-09-26 15:11
no test upload?

**Comment by CMCDragonkai** [comment] 2018-10-23 06:39
This assumes that the upload content type is a standard `multipart/form-data` or `application/x-www-form-urlencoded`. What if you are trying to upload all sorts of stuff like `application/x-tar`... etc?
